<Homepage>
    name: "Homepage"

    MDCard:
        size_hint: None, None
        size: 150, 80
        pos_hint: {'x': 0.32, 'top':0.96}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        Button:
            id: clear
            size_hint: (0.7, 0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'CLEAR'
            background_color: utils.get_color_from_hex('#FF3333')
        
        Button:
            id: tare
            size_hint: (0.7,0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'Tare'
            background_color: utils.get_color_from_hex('#33B7FF')
        
    MDCard:
        size_hint: None, None
        size: 150, 80
        pos_hint: {'x': 0.48, 'top':0.96}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        Button:
            id: profile
            size_hint: (0.7,0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'Profile'
            background_color: utils.get_color_from_hex('#33B7FF')
            on_release:
                app.root.current = "EditProfilePage"
                # root.manager.transition.direction = "left"

        Button:
            id: save
            size_hint: (0.7,0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'Save'
            background_color: utils.get_color_from_hex('#33B7FF')
    
    MDCard:
        size_hint: None, None
        size: 270, 80
        pos_hint: {'x': 0.65, 'top':0.96}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        MDLabel:
            text: "Calorie Tracker"
            font_size: 16
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: 5

        MDLabel:
            id: cal_tracker
            text: "O% Progress"

        ProgressBar:
            id: cal_tracker_bar
            min: 0
            max: 1
            pos_hint: {'x': 0}
            size_hint_x: 1
        


    FloatLayout:
        size_hint: (0.28, 0.2)
        pos_hint:{'x':0.02, 'top': 0.96}
        
        canvas.before:
            Color:
                rgba: 0.204, 0.204, 0.204, 1
            Line:
                width: 1.2
                rectangle: (self.x, self.y, self.width, self.height)
                
        Label:
            id: weight_input
            text: '0'
            bold: True
            font_size: 60
            color: 0.204, 0.204, 0.204, 1
            pos_hint:{'x':0.01, 'top': 1}
                    
    GridLayout:

        size_hint: (1, 0.6)
        pos_hint:{'x':0.02, 'top': 0.7}

        cols: 3
        rows: 2

        spacing: 40
        padding: 10

        #Row
        Button:
            size_hint: (.2, .2)
            background_color: 0,0,1,0
            
            on_release:
                root.createFruit()
                # root.manager.transition.direction = "left"
            
            Image:
                id: fruits_icon
                source: 'icons/fruits.png'
                center_x: self.parent.center_x
                center_y: self.parent.center_y

            # Edit: Let's try making a label
            
        Button:
            size_hint: (.2, .2)
            background_color: 0,0,1,0
            on_release:
                app.root.current = "CategoryPage"
                # root.manager.transition.direction = "left"
            
            Image:
                id: veg_icon
                source: 'icons/vegetable.png'
                center_x: self.parent.center_x
                center_y: self.parent.center_y

        Button:
            size_hint: (.2, .2)
            background_color: 0,0,1,0
            on_release:
                app.root.current = "CategoryPage"
                # root.manager.transition.direction = "left"

            Image:
                id: grains_icon
                source: 'icons/grains.png'
                center_x: self.parent.center_x
                center_y: self.parent.center_y
        
        Button:
            size_hint: (.2, .2)
            background_color: 0,0,1,0
            on_release:
                app.root.current = "CategoryPage"
                # root.manager.transition.direction = "left"
            
            Image:
                id: protein_icon
                source: 'icons/protein.png'
                center_x: self.parent.center_x
                center_y: self.parent.center_y
        
        Button:
            size_hint: (.2, .2)
            background_color: 0,0,1,0
            on_release:
                app.root.current = "CategoryPage"
                # root.manager.transition.direction = "left"
            
            Image:
                id: dairy_icon
                source: 'icons/dairy.png'
                center_x: self.parent.center_x
                center_y: self.parent.center_y
        
        Button:
            size_hint: (.2, .2)
            background_color: 0,0,1,0
            on_release:
                app.root.current = "MorePage"
                # root.manager.transition.direction = "left"
            Image:
                id: more_icon
                source: 'icons/more.png'
                center_x: self.parent.center_x
                center_y: self.parent.center_y

    # Food Category Labels
    MDCard:
        size_hint: None, None
        size: 60, 30
        pos_hint: {'x': 0.14, 'top':0.45}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        MDLabel:
            text: "Fruits"
            font_size: 12
            background_color: utils.get_color_from_hex('#09E4F5')
            halign: 'center'
    
    MDCard:
        size_hint: None, None
        size: 90, 30
        pos_hint: {'x': 0.47, 'top':0.45}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        MDLabel:
            text: "Vegetables"
            font_size: 12
            background_color: utils.get_color_from_hex('#09E4F5')
            halign: 'center'
    
    MDCard:
        size_hint: None, None
        size: 60, 30
        pos_hint: {'x': 0.82, 'top':0.45}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        MDLabel:
            text: "Grains"
            font_size: 12
            background_color: utils.get_color_from_hex('#09E4F5')
            halign: 'center'

    MDCard:
        size_hint: None, None
        size: 60, 30
        pos_hint: {'x': 0.14, 'top':0.13}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        MDLabel:
            text: "Protein"
            font_size: 12
            background_color: utils.get_color_from_hex('#09E4F5')
            halign: 'center'

    MDCard:
        size_hint: None, None
        size: 60, 30
        pos_hint: {'x': 0.48, 'top':0.13}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        MDLabel:
            text: "Dairy"
            font_size: 12
            background_color: utils.get_color_from_hex('#09E4F5')
            halign: 'center'

    MDCard:
        size_hint: None, None
        size: 60, 30
        pos_hint: {'x': 0.82, 'top':0.13}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        MDLabel:
            text: "More"
            font_size: 12
            background_color: utils.get_color_from_hex('#09E4F5')
            halign: 'center'