#: import utils kivy.utils

<CategoryPage>

    id: CategoryPage
    name: "CategoryPage"

    # Create the Nutrition Facts
    FloatLayout:
        size_hint: (0.28, 0.2)
        pos_hint:{'x':0.02, 'top': 0.96}
        
        canvas.before:
            Color:
                rgba: 0.204, 0.204, 0.204, 1
            Line:
                width: 1.2
                rectangle: (self.x, self.y, self.width, self.height)
                
###########################################################################    
        #   WEIGHT       
        MDLabel:
            id: weight_input
            text: '0'
            bold: True
            font_size: 60
            color: 0.204, 0.204, 0.204, 1
            pos_hint:{'x':0.01, 'top': 1}
    
    MDCard:
        size_hint: None, None
        size: 150, 80
        pos_hint: {'x': 0.32, 'top':0.96}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        # SAVE
        MDRoundFlatIconButton:
            id: save
            icon: "content-save"
            size_hint: (0.7,0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'Save'
            text_color: "black"
            on_release:
                root.enter_topButton("Save")

        
        # TARE
        MDRoundFlatIconButton:
            id: tare
            icon: "weight-gram"
            size_hint: (0.7,0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'Tare'
            text_color: "black"
        
    MDCard:
        size_hint: None, None
        size: 150, 80
        pos_hint: {'x': 0.48, 'top':0.96}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        # PROFILE
        MDRoundFlatIconButton:
            id: profile
            icon: "face-man-profile"
            size_hint: (0.7,0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'Profile'
            text_color: "black"

            on_release:
                app.root.generateEditProfilePageScreen()

        # HISTORY
        MDRoundFlatIconButton:
            id: foodHistory
            icon: "history"
            size_hint: (0.7, 0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'History'
            text_color: "black"

            on_release:
                app.root.generateFoodHistoryPageScreen()
                

    MDCard:
        size_hint: None, None
        size: 50, 80
        pos_hint: {'x': 0.65, 'top':0.96}
        orientation: 'vertical'
        
        # HELP
        MDFloatingActionButton:
            id: help
            icon: "help-circle"
            pos_hint: {'center_x':0.5 , 'top':0.96}
            md_bg_color: app.theme_cls.primary_color

            on_release:

    MDCard:
        size_hint: None, None
        size: 200, 80
        pos_hint: {'x': 0.72, 'top':0.96}
        padding: 5
        spacing: 5
        orientation: 'vertical'


        # CALORIE TRACKER
        MDLabel:
            text: "Calorie Tracker"
            id: tracker
            font_size: 16
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: 5

        MDLabel:
            id: user_goal
            text: ""

##############################################################
    # Fix Food List

    FloatLayout:

        size_hint: (0.65, 0.7)
        pos_hint:{'x':0.01, 'top':0.8}

        ScrollView:
            size: 400, 420

            GridLayout:
                id: foodList
                size_hint_y: None
                height: self.minimum_height
                width: 400
                cols: 2
                spacing: 10, 10
                padding: 10, 10
##############################################################
        
         
    # Display Nutrition Facts rectangle or box             
    MDCard:
        size_hint: None, None
        size: 240,300 
        pos_hint: {'x': 0.68, 'top':0.75}
        padding: 5
        spacing: 5
        orientation: 'vertical'
        elevation: 1

        MDLabel:
            text: "Nutrition Facts"
            bold: True
            halign: 'center'
        
        # Label Text
        # Edit: add holder with id on the right side
        MDLabel:
            text: "Edible Portion"
            id: food_edible
        
        MDLabel:
            text: "Calories"
            id: food_calories
        
        MDLabel:
            text: "Total Fat (g)"
            id: food_fat
        
        MDLabel:
            text: "Cholesterol (mg)"
            id: food_choles
        
        MDLabel:
            text: "Sodium (mg)"
            id: food_sodium
        
        MDLabel:
            text: "Total Carbohydrate (g)"
            id: food_carbo

        MDLabel:
            text: "Protein (g)"
            id: food_protein
        
        MDLabel:
            text: "Calcium (mg)"
            id: food_calcium
        
        MDLabel:
            text: "Iron (mg)"
            id: food_iron
    
    # Return button
    MDRectangleFlatIconButton:
        on_release:
            app.root.generateHomePageScreen()
