#:import utils kivy.utils

WindowManager:
    # SplashScreenPage:
    ProfilePage:
    Homepage:
    MealPlanPage:
    EditProfilePage:
    CategoryPage:
    MorePage:

# Widget Back Button
<MDRectangleFlatIconButton>
    text: "Back"
    icon: "page-previous"
    theme_text_color: "Custom"
    text_color: "blue"
    line_color: 0,0,0,0
    theme_icon_color: "Custom"
    icon_color: "blue"
    pos_hint: {"center_x": 0.94, "top": 0.98}

# Widget Nutrition Facts
<MDLabel>
    font_size: 14
    halign: 'left'
    size_hint_y: None
    height: self.texture_size[1]
    padding_y: 3

<SplashScreenPage>
    name: "SplashScreenPage"

    on_enter: self.ids.progress.start()

    FloatLayout:

        Image:
            source: 'icons/food.gif'
            allow_stretch: True
            anim_delay: 0
            anim_reset: True
        
        BoxLayout:
            pos_hint: {'center_y': .3, 'center_x': .5}
            padding: "10dp"
            size_hint_x: .7

            MDProgressBar:
                id: progress
                orientation: "horizontal"
                type: "indeterminate"
                running_duration: 1
                catching_duration: 1

<ProfilePage>
    name: "ProfilePage"

    user_name: user_name
    sex: sex
    age: age
    user_weight: user_weight
    user_height: user_height

    MDCard:
        size_hint: None, None
        size: 300, 350
        pos_hint: {'center_x': 0.5, 'center_y':0.5}
        elevation: 2
        padding: 10
        spacing: 10
        orientation: 'vertical'
        
        MDLabel:
            text: "Profile"
            font_size: 20
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: 5

        MDTextField:
            id: user_name
            mode: "round"         
            hint_text: "Name"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}

        # Edit: Change this to drop down 
        MDTextField:
            mode: "round"
            id: sex
            hint_text: "Sex"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}

        MDTextField:
            mode: "round"
            id: age
            hint_text: "Age"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}

        MDTextField:
            mode: "round"
            id: user_weight
            hint_text: "Weight"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}
        
        MDTextField:
            mode: "round"
            id: user_height
            hint_text: "Height"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}


        MDRoundFlatButton:
            text: "Save"
            font_size: 12
            pos_hint: {"center_x": 0.5}
            on_release:
                root.manager.transition.direction = "left"
                root.saveProfile()
        Widget:
            size_hint_y: None
            height: 10
            
<MealPlanPage>
    name: "MealPlanPage"

    # Label Design
    MDCard:
        size_hint: None, None
        size: 90, 50
        pos_hint: {'center_x': 0.5, 'top':0.96}
        orientation: 'vertical'

        MDLabel:
            text: "Meal Plans"
            font_size: 16
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: 5
        
        Widget:
            size_hint_y: None
            height: 10
    

    MDCard:
        size_hint: None, None
        size: 220, 300
        pos_hint: {'x': 0.03, 'y':0.1}
        elevation: 2
        padding: 10
        spacing: 10
        orientation: 'vertical'
    
    MDCard:
        size_hint: None, None
        size: 220, 300
        pos_hint: {'x': 0.36, 'y':0.1}
        elevation: 2
        padding: 10
        spacing: 10
        orientation: 'vertical'
    
    MDCard:
        size_hint: None, None
        size: 220, 300
        pos_hint: {'x': 0.68, 'y':0.1}
        elevation: 2
        padding: 10
        spacing: 10
        orientation: 'vertical'
    
    # Skip

    MDRectangleFlatButton:
        text: "Skip"
        theme_text_color: "Custom"
        text_color: "blue"
        line_color: "blue"
        pos_hint: {"center_x": 0.94, "center_y": 0.05}
        on_release:
            app.root.current = "Homepage"
            root.manager.transition.direction = "left"

<EditProfilePage>
    name: "EditProfilePage"

    # Profile
    MDCard:
        size_hint: None, None
        size: 300, 350
        pos_hint: {'x': 0.04, 'top':0.88}
        elevation: 1
        padding: 10
        spacing: 10
        orientation: 'vertical'
        
        MDLabel:
            text: "Profile"
            font_size: 20
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: 5

        # Edit this to label
        MDTextField:
            id: user_name
            mode: "round"         
            hint_text: "Name"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}

        MDTextField:
            mode: "round"
            id: sex
            hint_text: "Sex"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}

        MDTextField:
            mode: "round"
            id: age
            hint_text: "Age"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}

        MDTextField:
            mode: "round"
            id: user_weight
            hint_text: "Weight"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}
        
        MDTextField:
            mode: "round"
            id: user_height
            hint_text: "Height"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}
        
        MDRoundFlatButton:
            text: "Edit"
            font_size: 12
            pos_hint: {"center_x": 0.5}

        Widget:
            size_hint_y: None
            height: 10

    # Meal Plan
    MDCard:
        size_hint: None, None
        size: 400, 350
        pos_hint: {'x': 0.45, 'top':0.88}
        elevation: 1
        padding: 10
        spacing: 10
        orientation: 'vertical'

        MDLabel:
            text: "Meal Plans"
            font_size: 20
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: 5
        
        ScrollView:
            GridLayout:
                cols: 1
                spacing: 10
                pading: 10

            # List or Card of Meal Plans

    # Return
    MDRectangleFlatIconButton:
        on_release:
            app.root.current = "Homepage"
            root.manager.transition.direction = "right"

<Homepage>
    name: "Homepage"

    MDCard:
        size_hint: None, None
        size: 150, 80
        pos_hint: {'x': 0.32, 'top':0.96}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        Button:
            id: clear
            size_hint: (0.7, 0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'CLEAR'
            background_color: utils.get_color_from_hex('#FF3333')
        
        Button:
            id: tare
            size_hint: (0.7,0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'Tare'
            background_color: utils.get_color_from_hex('#33B7FF')
        
    MDCard:
        size_hint: None, None
        size: 150, 80
        pos_hint: {'x': 0.48, 'top':0.96}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        Button:
            id: profile
            size_hint: (0.7,0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'Profile'
            background_color: utils.get_color_from_hex('#33B7FF')
            on_release:
                app.root.current = "EditProfilePage"
                root.manager.transition.direction = "left"

        Button:
            id: save
            size_hint: (0.7,0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'Save'
            background_color: utils.get_color_from_hex('#33B7FF')
    
    MDCard:
        size_hint: None, None
        size: 270, 80
        pos_hint: {'x': 0.65, 'top':0.96}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        MDLabel:
            text: "Calorie Tracker"
            font_size: 16
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: 5

        MDLabel:
            id: cal_tracker
            text: "O% Progress"

        ProgressBar:
            id: cal_tracker_bar
            min: 0
            max: 1
            pos_hint: {'x': 0}
            size_hint_x: 1
        


    FloatLayout:
        size_hint: (0.28, 0.2)
        pos_hint:{'x':0.02, 'top': 0.96}
        
        canvas.before:
            Color:
                rgba: 0.204, 0.204, 0.204, 1
            Line:
                width: 1.2
                rectangle: (self.x, self.y, self.width, self.height)
                
        Label:
            id: weight_input
            text: '0'
            bold: True
            font_size: 60
            color: 0.204, 0.204, 0.204, 1
            pos_hint:{'x':0.01, 'top': 1}
                    
    GridLayout:

        size_hint: (1, 0.6)
        pos_hint:{'x':0.02, 'top': 0.7}

        cols: 3
        rows: 2

        spacing: 40
        padding: 10

        #Row
        Button:
            size_hint: (.2, .2)
            background_color: 0,0,1,0
            on_release:
                app.root.current = "CategoryPage"
                root.manager.transition.direction = "left"
            
            Image:
                id: fruits_icon
                source: 'icons/fruits.png'
                center_x: self.parent.center_x
                center_y: self.parent.center_y

            # Edit: Let's try making a label
            
        Button:
            size_hint: (.2, .2)
            background_color: 0,0,1,0
            on_release:
                app.root.current = "CategoryPage"
                root.manager.transition.direction = "left"
            
            Image:
                id: veg_icon
                source: 'icons/vegetable.png'
                center_x: self.parent.center_x
                center_y: self.parent.center_y

        Button:
            size_hint: (.2, .2)
            background_color: 0,0,1,0
            on_release:
                app.root.current = "CategoryPage"
                root.manager.transition.direction = "left"

            Image:
                id: grains_icon
                source: 'icons/grains.png'
                center_x: self.parent.center_x
                center_y: self.parent.center_y
        
        Button:
            size_hint: (.2, .2)
            background_color: 0,0,1,0
            on_release:
                app.root.current = "CategoryPage"
                root.manager.transition.direction = "left"
            
            Image:
                id: protein_icon
                source: 'icons/protein.png'
                center_x: self.parent.center_x
                center_y: self.parent.center_y
        
        Button:
            size_hint: (.2, .2)
            background_color: 0,0,1,0
            on_release:
                app.root.current = "CategoryPage"
                root.manager.transition.direction = "left"
            
            Image:
                id: dairy_icon
                source: 'icons/dairy.png'
                center_x: self.parent.center_x
                center_y: self.parent.center_y
        
        Button:
            size_hint: (.2, .2)
            background_color: 0,0,1,0
            on_release:
                app.root.current = "MorePage"
                root.manager.transition.direction = "left"
            Image:
                id: more_icon
                source: 'icons/more.png'
                center_x: self.parent.center_x
                center_y: self.parent.center_y

    # Food Category Labels
    MDCard:
        size_hint: None, None
        size: 60, 30
        pos_hint: {'x': 0.14, 'top':0.45}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        MDLabel:
            text: "Fruits"
            font_size: 12
            background_color: utils.get_color_from_hex('#09E4F5')
            halign: 'center'
    
    MDCard:
        size_hint: None, None
        size: 90, 30
        pos_hint: {'x': 0.47, 'top':0.45}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        MDLabel:
            text: "Vegetables"
            font_size: 12
            background_color: utils.get_color_from_hex('#09E4F5')
            halign: 'center'
    
    MDCard:
        size_hint: None, None
        size: 60, 30
        pos_hint: {'x': 0.82, 'top':0.45}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        MDLabel:
            text: "Grains"
            font_size: 12
            background_color: utils.get_color_from_hex('#09E4F5')
            halign: 'center'

    MDCard:
        size_hint: None, None
        size: 60, 30
        pos_hint: {'x': 0.14, 'top':0.13}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        MDLabel:
            text: "Protein"
            font_size: 12
            background_color: utils.get_color_from_hex('#09E4F5')
            halign: 'center'

    MDCard:
        size_hint: None, None
        size: 60, 30
        pos_hint: {'x': 0.48, 'top':0.13}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        MDLabel:
            text: "Dairy"
            font_size: 12
            background_color: utils.get_color_from_hex('#09E4F5')
            halign: 'center'

    MDCard:
        size_hint: None, None
        size: 60, 30
        pos_hint: {'x': 0.82, 'top':0.13}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        MDLabel:
            text: "More"
            font_size: 12
            background_color: utils.get_color_from_hex('#09E4F5')
            halign: 'center'

<CategoryPage>
    name: "CategoryPage"

    # food_name: food_name
    # common_name: common_name

    MDFloatingActionButtonSpeedDial:
        id: speed_dial
        data: app.data
        root_button_anim: True
        hint_animation: True   
        
    # Create the Nutrition Facts
    FloatLayout:
        size_hint: (0.28, 0.2)
        pos_hint:{'x':0.02, 'top': 0.96}
        
        canvas.before:
            Color:
                rgba: 0.204, 0.204, 0.204, 1
            Line:
                width: 1.2
                rectangle: (self.x, self.y, self.width, self.height)
                
        Label:
            text: '0'
            bold: True
            font_size: 60
            color: 0.204, 0.204, 0.204, 1
            pos_hint:{'x':0.01, 'top': 1}
    
    MDCard:
        size_hint: None, None
        size: 150, 80
        pos_hint: {'x': 0.32, 'top':0.96}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        Button:
            id: clear
            size_hint: (0.7, 0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'CLEAR'
            background_color: utils.get_color_from_hex('#ff3333')
        
        Button:
            id: tare
            size_hint: (0.7,0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'Tare'
        
    MDCard:
        size_hint: None, None
        size: 150, 80
        pos_hint: {'x': 0.48, 'top':0.96}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        Button:
            id: profile
            size_hint: (0.7,0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'Profile'
            on_release:
                app.root.current = "EditProfilePage"
                root.manager.transition.direction = "left"

        Button:
            id: save
            size_hint: (0.7,0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'Save'
    
    MDCard:
        size_hint: None, None
        size: 270, 80
        pos_hint: {'x': 0.65, 'top':0.96}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        MDLabel:
            text: "Calorie Tracker"
            font_size: 16
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: 5

        MDLabel:
            id: cal_tracker
            text: "O% Progress"

        ProgressBar:
            id: cal_tracker_bar
            min: 0
            max: 1
            pos_hint: {'x': 0}
            size_hint_x: 1

    # Fix Food List

    FloatLayout:
        size_hint: (0.65, 0.7)
        pos_hint:{'x':0.01, 'top':0.8}

        ScrollView:
            size: 400, 420
            pos_hint:{'x':0.01, 'top': 0.8}

            GridLayout:
                size_hint_y: None
                height: root.height
                width: 400
                cols: 1
                spacing: "10dp"
                padding: "10dp"
                


                    

    # Display Nutrition Facts rectangle or box             
    MDCard:
        size_hint: None, None
        size: 240,300 
        pos_hint: {'x': 0.68, 'top':0.75}
        padding: 5
        spacing: 5
        orientation: 'vertical'
        elevation: 1

        MDLabel:
            text: "Nutrition Facts"
            bold: True
            halign: 'center'
        
        # Label Text
        # Edit: add holder with id on the right side
        MDLabel:
            text: "Serving Size"
        
        MDLabel:
            text: "Calories"
        
        MDLabel:
            text: "Total Fat (g)"
        
        MDLabel:
            text: "Cholesterol (mg)"
        
        MDLabel:
            text: "Sodium (mg)"
        
        MDLabel:
            text: "Total Carbohydrate (g)"

        MDLabel:
            text: "Protein (g)"
        
        MDLabel:
            text: "Calcium (mg)"
        
        MDLabel:
            text: "Iron (mg)"
    
    MDCard:
        size_hint: None, None
        size: 97,248 
        pos_hint: {'x': 0.84, 'top':0.63}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        MDLabel: # This is empty
            text: " "
            halign: 'center'
        
        # Label Text
        MDLabel:
            text: " 0 "
            id: food_serving_size
            halign: "right"
        
        MDLabel:
            text: " 0 "
            id: food_calories
            halign: "right"
        
        MDLabel:
            text: " 0 "
            id: food_fat
            halign: "right"
        
        MDLabel:
            text: " 0 "
            id: food_choles
            halign: "right"
        
        MDLabel:
            text: " 0 "
            id: food_sodium
            halign: "right"
        
        MDLabel:
            text: " 0 "
            id: food_carbo
            halign: "right"
        
        MDLabel:
            text: " 0 "
            id: food_protein
            halign: "right"
        
        MDLabel:
            text: " 0 "
            id: food_calcium
            halign: "right"
        
        MDLabel:
            text: " 0 "
            id: food_iron
            halign: "right"

    # Return button
    MDRectangleFlatIconButton:
        on_release:
            app.root.current = "Homepage"
            root.manager.transition.direction = "right"

<MorePage>
    name: "MorePage"

    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        Label:
            text: "More"
            font_size: 32
    
    # Return button
    MDRectangleFlatIconButton:
        on_release:
            app.root.current = "Homepage"
            root.manager.transition.direction = "right"


