<WindowManager>:
    id: wm

    Screen:
        id: Homepage
        name: "Homepage"

    Screen:
        id: CategoryPage
        name: "CategoryPage"
    
    Screen:
        id: MealPlanPage
        name: "MealPlanPage"
    
    Screen:
        id: ProfilePage
        name: "ProfilePage"
    
    Screen:
        id: EditProfilePage
        name: "EditProfilePage"

    Screen:
        id: MorePage
        name: "MorePage"
    
