#:import utils kivy.utils

WindowManager:
    AccountPage:
    ProfilePage:
    Homepage:
    MealPlanPage:
    EditProfilePage:
    CategoryPage:
    MorePage:

# Widget Back Button
<MDRectangleFlatIconButton>
    text: "Back"
    icon: "page-previous"
    theme_text_color: "Custom"
    text_color: "blue"
    line_color: 0,0,0,0
    theme_icon_color: "Custom"
    icon_color: "blue"
    pos_hint: {"center_x": 0.94, "top": 0.98}

<AccountPage>
    name: "AccountPage"
    
    # User Profile
    MDCard:
        size_hint: None, None
        size: 300, 350
        pos_hint: {'center_x': 0.5, 'center_y':0.5}
        elevation: 2
        padding: 20
        spacing: 20
        orientation: 'vertical'
        
        MDLabel:
            text: "Welcome"
            font_size: 20
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: 5

        MDTextField:
            mode: 'round'
            id: user
            hint_text: "username"
            icon_right: "account"
            size_hint_x: None
            width: 200
            font_size: 18
            pos_hint: {"center_x": 0.5}

        MDTextField:
            mode: 'round'
            id: password
            hint_text: "password"
            icon_right: "eye-off"
            size_hint_x: None
            width: 200
            font_size: 18
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            password: True

        MDRoundFlatButton:
            text: "LOG IN"
            font_size: 12
            pos_hint: {"center_x": 0.5}
            on_release:
                app.root.current = "ProfilePage"
                root.manager.transition.direction = "left"


        Widget:
            size_hint_y: None
            height: 20

<ProfilePage>
    name: "ProfilePage"

    MDCard:
        size_hint: None, None
        size: 300, 350
        pos_hint: {'center_x': 0.5, 'center_y':0.5}
        elevation: 2
        padding: 10
        spacing: 10
        orientation: 'vertical'
        
        MDLabel:
            text: "Profile"
            font_size: 20
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: 5

        MDTextField:
            id: user_name
            mode: "round"         
            hint_text: "Name"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}

        MDTextField:
            mode: "round"
            id: sex
            hint_text: "Sex"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}

        MDTextField:
            mode: "round"
            id: age
            hint_text: "Age"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}

        MDTextField:
            mode: "round"
            id: user_weight
            hint_text: "Weight"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}
        
        MDTextField:
            mode: "round"
            id: user_height
            hint_text: "Height"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}


        MDRoundFlatButton:
            text: "Save"
            font_size: 12
            pos_hint: {"center_x": 0.5}
            on_release:
                app.root.current = "MealPlanPage"
                root.manager.transition.direction = "left"

        Widget:
            size_hint_y: None
            height: 10

<MealPlanPage>
    name: "MealPlanPage"

    # Label Design
    MDCard:
        size_hint: None, None
        size: 90, 50
        pos_hint: {'center_x': 0.5, 'top':0.96}
        orientation: 'vertical'

        MDLabel:
            text: "Meal Plans"
            font_size: 16
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: 5
        
        Widget:
            size_hint_y: None
            height: 10
    

    MDCard:
        size_hint: None, None
        size: 220, 300
        pos_hint: {'x': 0.03, 'y':0.1}
        elevation: 2
        padding: 10
        spacing: 10
        orientation: 'vertical'
    
    MDCard:
        size_hint: None, None
        size: 220, 300
        pos_hint: {'x': 0.36, 'y':0.1}
        elevation: 2
        padding: 10
        spacing: 10
        orientation: 'vertical'
    
    MDCard:
        size_hint: None, None
        size: 220, 300
        pos_hint: {'x': 0.68, 'y':0.1}
        elevation: 2
        padding: 10
        spacing: 10
        orientation: 'vertical'
    
    # Skip

    MDRectangleFlatButton:
        text: "Skip"
        theme_text_color: "Custom"
        text_color: "blue"
        line_color: "blue"
        pos_hint: {"center_x": 0.94, "center_y": 0.05}
        on_release:
            app.root.current = "Homepage"
            root.manager.transition.direction = "left"

<EditProfilePage>
    name: "EditProfilePage"

    # Profile
    MDCard:
        size_hint: None, None
        size: 300, 350
        pos_hint: {'x': 0.04, 'top':0.88}
        elevation: 1
        padding: 10
        spacing: 10
        orientation: 'vertical'
        
        MDLabel:
            text: "Profile"
            font_size: 20
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: 5

        # Edit this to label
        MDTextField:
            id: user_name
            mode: "round"         
            hint_text: "Name"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}

        MDTextField:
            mode: "round"
            id: sex
            hint_text: "Sex"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}

        MDTextField:
            mode: "round"
            id: age
            hint_text: "Age"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}

        MDTextField:
            mode: "round"
            id: user_weight
            hint_text: "Weight"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}
        
        MDTextField:
            mode: "round"
            id: user_height
            hint_text: "Height"
            size_hint_x: None
            width: 200
            font_size: 14
            pos_hint: {"center_x": 0.5}
        
        MDRoundFlatButton:
            text: "Edit"
            font_size: 12
            pos_hint: {"center_x": 0.5}

        Widget:
            size_hint_y: None
            height: 10

    # Meal Plan
    MDCard:
        size_hint: None, None
        size: 400, 350
        pos_hint: {'x': 0.45, 'top':0.88}
        elevation: 1
        padding: 10
        spacing: 10
        orientation: 'vertical'

        MDLabel:
            text: "Meal Plans"
            font_size: 20
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: 5
        
        ScrollView:
            GridLayout:
                cols: 1
                spacing: 10
                pading: 10

            # List or Card of Meal Plans

    # Return
    MDRectangleFlatIconButton:
        on_release:
            app.root.current = "Homepage"
            root.manager.transition.direction = "right"

<Homepage>
    name: "Homepage"

    MDCard:
        size_hint: None, None
        size: 150, 80
        pos_hint: {'x': 0.32, 'top':0.96}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        Button:
            id: clear
            size_hint: (0.7, 0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'CLEAR'
            background_color: utils.get_color_from_hex('#FF3333')
        
        Button:
            id: tare
            size_hint: (0.7,0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'Tare'
            background_color: utils.get_color_from_hex('#33B7FF')
        
    MDCard:
        size_hint: None, None
        size: 150, 80
        pos_hint: {'x': 0.48, 'top':0.96}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        Button:
            id: profile
            size_hint: (0.7,0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'Profile'
            background_color: utils.get_color_from_hex('#33B7FF')
            on_release:
                app.root.current = "EditProfilePage"
                root.manager.transition.direction = "left"

        Button:
            id: save
            size_hint: (0.7,0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'Save'
            background_color: utils.get_color_from_hex('#33B7FF')
    
    MDCard:
        size_hint: None, None
        size: 270, 80
        pos_hint: {'x': 0.65, 'top':0.96}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        MDLabel:
            text: "Calorie Tracker"
            font_size: 16
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: 5

        MDLabel:
            id: cal_tracker
            text: "O% Progress"

        ProgressBar:
            id: cal_tracker_bar
            min: 0
            max: 1
            pos_hint: {'x': 0}
            size_hint_x: 1
        
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        

        # Display Weight
        TextInput:
            id: weight_input
            text: "0"
            font_size: 40
            size_hint: (0.3, 0.3)
            pos_hint:{'x':0.02}
            spacing: 10
            padding: 10
                
    
        GridLayout:
            cols: 3
            rows: 2

            spacing: 10
            padding: 10

            #Row
            Button:
                size_hint: (.2, .2)
                background_color: 0,0,1,0
                on_release:
                    app.root.current = "CategoryPage"
                    root.manager.transition.direction = "left"
                
                Image:
                    id: fruits_icon
                    source: 'icons/fruits.png'
                    center_x: self.parent.center_x
                    center_y: self.parent.center_y
                
            Button:
                size_hint: (.2, .2)
                background_color: 0,0,1,0
                on_release:
                    app.root.current = "CategoryPage"
                    root.manager.transition.direction = "left"
                
                Image:
                    id: veg_icon
                    source: 'icons/vegetable.png'
                    center_x: self.parent.center_x
                    center_y: self.parent.center_y
            
            Button:
                size_hint: (.2, .2)
                background_color: 0,0,1,0
                on_release:
                    app.root.current = "CategoryPage"
                    root.manager.transition.direction = "left"

                Image:
                    id: grains_icon
                    source: 'icons/grains.png'
                    center_x: self.parent.center_x
                    center_y: self.parent.center_y
            
            Button:
                size_hint: (.2, .2)
                background_color: 0,0,1,0
                on_release:
                    app.root.current = "CategoryPage"
                    root.manager.transition.direction = "left"
                
                Image:
                    id: protein_icon
                    source: 'icons/protein.png'
                    center_x: self.parent.center_x
                    center_y: self.parent.center_y
            
            Button:
                size_hint: (.2, .2)
                background_color: 0,0,1,0
                on_release:
                    app.root.current = "CategoryPage"
                    root.manager.transition.direction = "left"
                
                Image:
                    id: dairy_icon
                    source: 'icons/dairy.png'
                    center_x: self.parent.center_x
                    center_y: self.parent.center_y
            
            Button:
                size_hint: (.2, .2)
                background_color: 0,0,1,0
                text: "More"
                on_release:
                    app.root.current = "MorePage"
                    root.manager.transition.direction = "left"
                Image:
                    id: more_icon
                    source: 'icons/more.png'
                    center_x: self.parent.center_x
                    center_y: self.parent.center_y
                 
<CategoryPage>
    name: "CategoryPage"

    # Create the Nutrition Facts
    FloatLayout:
        size_hint: (0.3, 0.3)
        pos_hint:{'x':0.02, 'top': 1}
        
        # Edit: Dli ma center ang label 

        Label:
            # center: root.center
            # halign: 'center'
            # text: '0'
            bold: True
            font_size: 60
            color: 0.204, 0.204, 0.204, 1
            pos_hint:{'x':0.01, 'top': 1}
            
            # Line
            canvas.before:
                Color:
                    rgba: 0.204, 0.204, 0.204, 1
                Line:
                    width: 1.2
                    rectangle: (self.x, self.y, 200, 100)
    
    MDCard:
        size_hint: None, None
        size: 150, 80
        pos_hint: {'x': 0.32, 'top':0.96}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        Button:
            id: clear
            size_hint: (0.7, 0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'CLEAR'
            background_color: utils.get_color_from_hex('#ff3333')
        
        Button:
            id: tare
            size_hint: (0.7,0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'Tare'
        
    MDCard:
        size_hint: None, None
        size: 150, 80
        pos_hint: {'x': 0.48, 'top':0.96}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        Button:
            id: profile
            size_hint: (0.7,0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'Profile'
            on_release:
                app.root.current = "EditProfilePage"
                root.manager.transition.direction = "left"

        Button:
            id: save
            size_hint: (0.7,0.7)
            pos_hint: {'center_x':0.5 , 'center_y':0.5}
            text: 'Save'
    
    MDCard:
        size_hint: None, None
        size: 270, 80
        pos_hint: {'x': 0.65, 'top':0.96}
        padding: 5
        spacing: 5
        orientation: 'vertical'

        MDLabel:
            text: "Calorie Tracker"
            font_size: 16
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: 5

        MDLabel:
            id: cal_tracker
            text: "O% Progress"

        ProgressBar:
            id: cal_tracker_bar
            min: 0
            max: 1
            pos_hint: {'x': 0}
            size_hint_x: 1

    # Fix Food List

    FloatLayout:
        size_hint: (0.65, 0.7)
        pos_hint:{'x':0.01, 'top':0.8}

        ScrollView:
            size: 400, 420
            pos_hint:{'x':0.01, 'top': 0.8}

            GridLayout:
                size_hint_y: None
                height: root.height
                width: 400
                cols: 1
                spacing: "10dp"
                padding: "10dp"
                
                MDList:
                    id: food
                        

    # Return button
    MDRectangleFlatIconButton:
        on_release:
            app.root.current = "Homepage"
            root.manager.transition.direction = "right"

<MorePage>
    name: "MorePage"

    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        Label:
            text: "More"
            font_size: 32
    
    # Return button
    MDRectangleFlatIconButton:
        on_release:
            app.root.current = "Homepage"
            root.manager.transition.direction = "right"
